#!/usr/bin/env bash
#Q5 Echo 1-10 
x=1
while [ $x -le 10 ]
do
    if [ $x = 4 ]
    then echo "bad luck"
	 ((x++))
    elif [ $x = 8 ]
    then echo "good luck"
	((x++))
    else
	echo "Best School"
	((x++))
	fi
done
